### ISSUE TITLE
Olha o disco voador

### ISSUE THREAD

**Issue by MOB-atheist** [LucasAlvaresA/Exercicios#1]
Olha o disco voador

<div style="
    position: relative;
    padding: 100px;
">
    <div style="position: absolute;background-color: black;width: 100px;height: 100px;border-radius: 100%;">
        <div style="position: absolute;background-color: black;width: 200px;height: 50px;border-radius: 100px 100px 0 0;left: -50px;bottom: 0px;">
        </div>
    </div>
</div>

**Comment by LucasAlvaresA** [comment]
vruuummm
